apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hmzm3qyie-go
  janus-idp.io/tekton: hmzm3qyie-go
  backstage.io/kubernetes-id: hmzm3qyie-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hmzm3qyie-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
